add refresh-config feature

diff --git a/scripts/bin/tfexe b/scripts/bin/tfexe
--- a/scripts/bin/tfexe
+++ b/scripts/bin/tfexe
@@ -10,6 +10,7 @@
 # tfexe import # import existing vnet into state file
 # tfexe generate-config # generate config.yaml file based on inputs
 # tfexe deploy # deploy azure resource based on settings.yaml file and inputs
+# tfexe refresh-config # refresh config.yaml file to match the current state of the infrastructure
 
 # Begin Functions
 exec_terraform() {
@@ -19,10 +20,10 @@ exec_terraform() {
   local TF_VAR_FILE=$3
   local TF_VARS=("${@:4}")
 
-  if [[ "$ACTION" == *"init"* || "$ACTION" == *"plan"* || "$ACTION" == *"apply"* || "$ACTION" == *"import"*  || "$ACTION" == *"generate-config"* || "$ACTION" == *"deploy"*  ]]; then
+  if [[ "$ACTION" == *"init"* || "$ACTION" == *"plan"* || "$ACTION" == *"apply"* || "$ACTION" == *"import"*  || "$ACTION" == *"generate-config"* || "$ACTION" == *"deploy"* || "$ACTION" == *"refresh-config"* ]]; then
     # alway exec terraform init
 
-    if [[ "$ACTION" != *"import"* && "$ACTION" != *"generate-config"* && "$ACTION" != *"deploy"* ]]; then
+    if [[ "$ACTION" != *"import"* && "$ACTION" != *"generate-config"* && "$ACTION" != *"deploy"* && "$ACTION" != *"refresh-config"* ]]; then
 
       echo "Using config file: $TF_CONFIG"
       PREFIX=$(yq  -r '.prefix' $TF_CONFIG)
@@ -167,6 +168,23 @@ exec_terraform() {
       echo -e "\e[32mTerraform $ACTION succeeded!\e[0m"
     fi    
 
+  elif [[ "$ACTION" == *"refresh-config"* ]]; then
+    echo "Go to working directory /tf/avm/templates/landingzone/configuration/0-launchpad/launchpad_healthcare/scripts"
+    echo "Running..."
+    echo "./refresh_config.sh"
+    echo "     "
+    # execute from current folder or -path parameter if exists
+    cd /tf/avm/templates/landingzone/configuration/0-launchpad/launchpad_healthcare/scripts
+    ./refresh_config.sh  # Check if the command was successful
+    if [ $? -ne 0 ]; then
+      echo -e "     "
+      echo -e "\e[31mTerraform $ACTION failed. Exiting.\e[0m"
+      exit 1
+    else
+      echo -e "     "
+      echo -e "\e[32mTerraform $ACTION succeeded!\e[0m"
+    fi    
+
   elif [[ "$ACTION" == *"deploy"* ]]; then
     echo "Go to working directory /tf/avm/scripts/bin"
     echo "Running..."
@@ -192,7 +210,7 @@ exec_terraform() {
 
 # Check if at least 2 arguments are provided
 if [[ $# -lt 1 ]]; then
-    echo "Usage: tfexe <init|apply|plan|import|generate-config|deploy> [-var=key=value | -path=path | -config=configpath]..."
+    echo "Usage: tfexe <init|apply|plan|import|generate-config|deploy|refresh-config> [-var=key=value | -path=path | -config=configpath]..."
     echo " "
     echo "The available commands for execution are listed below."
     echo "The primary workflow commands are given first, followed by"
@@ -205,10 +223,7 @@ if [[ $# -lt 1 ]]; then
     echo "  import          Import existing VNET infrastructure into your Terraform state"
     echo "  generate-config Generate config.yaml file based on inputs"
     echo "  deploy          Deploy azure resource based on settings.yaml file and prompt inputs"
-
-
-# tfexe generate-config # generate config.yaml file based on inputs
-# tfexe deploy # deploy azure resource based on settings.yaml file and inputs
+    echo "  refresh-config  Refresh config.yaml file to match the current state of the infrastructure"
 
     echo " "
     echo "All other commands:"
@@ -231,6 +246,7 @@ if [[ $# -lt 1 ]]; then
     echo "tfexe import"
     echo "tfexe generate-config"
     echo "tfexe deploy"
+    echo "tfexe refresh-config"
     exit 1
 fi
 
@@ -238,8 +254,8 @@ fi
 ACTION=$1
 shift
 
-if [[ "$ACTION" != "apply" && "$ACTION" != "plan" && "$ACTION" != "init"  && "$ACTION" != "import"  && "$ACTION" != "generate-config" && "$ACTION" != "deploy" ]]; then
-    echo -e "\e[31mError: First parameter must be 'init' or 'apply' or 'plan' or 'import' or 'generate-config' or 'deploy'\e[0m"
+if [[ "$ACTION" != "apply" && "$ACTION" != "plan" && "$ACTION" != "init"  && "$ACTION" != "import"  && "$ACTION" != "generate-config" && "$ACTION" != "deploy" && "$ACTION" != "refresh-config" ]]; then
+    echo -e "\e[31mError: First parameter must be 'init' or 'apply' or 'plan' or 'import' or 'generate-config' or 'deploy' or 'refresh-config'\e[0m"
     exit 1
 fi
 
