Update tfexe

diff --git a/scripts/bin/tfexe b/scripts/bin/tfexe
--- a/scripts/bin/tfexe
+++ b/scripts/bin/tfexe
@@ -1,12 +1,13 @@
 #!/bin/bash
 
 # example:
-# tfexec plan -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr
-# tfexec apply -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr
-# tfexec plan -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr -var="prefix=hubspoke -var=location=westus2"
-# tfexec apply -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr -var="prefix=hubspoke -var=location=westus2"
-# tfexec apply run-all -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project"
-# tfexec apply run-all -include=/tf/avm/config/path.hcl"
+# tfexe plan -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr
+# tfexe apply -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr
+# tfexe plan -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr -var="prefix=hubspoke -var=location=westus2"
+# tfexe apply -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr -var="prefix=hubspoke -var=location=westus2"
+# tfexe apply run-all -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project"
+# tfexe apply run-all -include=/tf/avm/config/path.hcl"
+# tfexe import # import existing vnet into state file
 
 # Begin Functions
 exec_terraform() {
@@ -14,7 +15,7 @@ exec_terraform() {
   local ACTION=$1
   local TF_CONFIG=$2
 
-  if [[ "$ACTION" == *"init"* || "$ACTION" == *"plan"* || "$ACTION" == *"apply"* ]]; then
+  if [[ "$ACTION" == *"init"* || "$ACTION" == *"plan"* || "$ACTION" == *"apply"* || "$ACTION" == *"import"* ]]; then
     # alway exec terraform init
 
     # PREFIX=$(yq  -r '.prefix' /tf/avm/templates/landingzone/configuration/0-launchpad/scripts/config.yaml)
@@ -114,13 +115,30 @@ exec_terraform() {
     fi
   fi
 
+  elif [[ "$ACTION" == *"import"* ]]; then
+    echo "     "
+    echo "Running..."
+    echo "./scripts/import_app_lz.sh"
+    echo "     "
+    cd /tf/avm/templates/landingzone/configuration/0-launchpad/launchpad
+    ./scripts/import_app_lz.sh  # Check if the command was successful
+    if [ $? -ne 0 ]; then
+      echo -e "     "
+      echo -e "\e[31mTerraform $ACTION failed. Exiting.\e[0m"
+      exit 1
+    else
+      echo -e "     "
+      echo -e "\e[32mTerraform $ACTION succeeded!\e[0m"
+    fi    
+  fi  
+
 }
 
 # End Functions
 
 # Check if at least 2 arguments are provided
 if [[ $# -lt 1 ]]; then
-    echo "Usage: aztfexec <init|apply|plan> [-var=key=value | -path=path | -config=configpath]..."
+    echo "Usage: tfexe <init|apply|plan> [-var=key=value | -path=path | -config=configpath]..."
     echo " "
     echo "The available commands for execution are listed below."
     echo "The primary workflow commands are given first, followed by"
@@ -130,6 +148,7 @@ if [[ $# -lt 1 ]]; then
     echo "  init          Prepare your working directory for other commands"
     echo "  plan          Execute init and then show changes required by the current configuration"
     echo "  apply         Execute init and then create or update infrastructure"
+    echo "  import        Import existing VNET infrastructure into your Terraform state"
     echo " "
     echo "All other commands:"
     echo "  run-all    Execute all the solution accelerators of all sub-folders under this parent folder"
@@ -139,13 +158,14 @@ if [[ $# -lt 1 ]]; then
     echo "  -var        Set a variable in the Terraform configuration"
     echo " "
     echo "Example: "
-    echo "aztfexec init -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr"  
-    echo "aztfexec plan -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr"  
-    echo "aztfexec apply -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr -var=resource_names=[\"web\"] "       
-    echo "aztfexec apply -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr -config=/tf/avm/scripts/templates/config.yaml"
-    echo "aztfexec apply" 
-    echo "aztfexec apply run-all -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project"
-    echo "aztfexec apply run-all -include=/tf/avm/config/path.hcl"
+    echo "tfexe init -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr"  
+    echo "tfexe plan -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr"  
+    echo "tfexe apply -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr -var=resource_names=[\"web\"] "       
+    echo "tfexe apply -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project/acr -config=/tf/avm/scripts/templates/config.yaml"
+    echo "tfexe apply" 
+    echo "tfexe apply run-all -path=/tf/avm/templates/landingzone/configuration/2-solution_accelerators/project"
+    echo "tfexe apply run-all -include=/tf/avm/config/path.hcl"
+    echo "tfexe import"
     exit 1
 fi
 
@@ -153,7 +173,7 @@ fi
 ACTION=$1
 shift
 
-if [[ "$ACTION" != "apply" && "$ACTION" != "plan" && "$ACTION" != "init" ]]; then
+if [[ "$ACTION" != "apply" && "$ACTION" != "plan" && "$ACTION" != "init"  && "$ACTION" != "import" ]]; then
     echo -e "\e[31mError: First parameter must be 'int' or 'apply' or 'plan'\e[0m"
     exit 1
 fi
