add deploy.sh and add cmd to tfexe

diff --git a/scripts/bin/tfexe b/scripts/bin/tfexe
--- a/scripts/bin/tfexe
+++ b/scripts/bin/tfexe
@@ -9,6 +9,7 @@
 # tfexe apply run-all -include=/tf/avm/config/path.hcl"
 # tfexe import # import existing vnet into state file
 # tfexe generate-config # generate config.yaml file based on inputs
+# tfexe deploy # deploy azure resource based on settings.yaml file and inputs
 
 # Begin Functions
 exec_terraform() {
@@ -16,7 +17,7 @@ exec_terraform() {
   local ACTION=$1
   local TF_CONFIG=$2
 
-  if [[ "$ACTION" == *"init"* || "$ACTION" == *"plan"* || "$ACTION" == *"apply"* || "$ACTION" == *"import"*  || "$ACTION" == *"generate-config"* ]]; then
+  if [[ "$ACTION" == *"init"* || "$ACTION" == *"plan"* || "$ACTION" == *"apply"* || "$ACTION" == *"import"*  || "$ACTION" == *"generate-config"* || "$ACTION" == *"deploy"*  ]]; then
     # alway exec terraform init
 
     # PREFIX=$(yq  -r '.prefix' /tf/avm/templates/landingzone/configuration/0-launchpad/scripts/config.yaml)
@@ -53,7 +54,7 @@ exec_terraform() {
 
     fi
 
-    if [[ "$ACTION" != *"import"* && "$ACTION" != *"generate-config"* ]]; then
+    if [[ "$ACTION" != *"import"* && "$ACTION" != *"generate-config"* && "$ACTION" != *"deploy"* ]]; then
       # Store the command in a variable
       cmdexecute="terraform init -reconfigure \
         -backend-config=\"resource_group_name=${RG_NAME}\" \
@@ -139,6 +140,7 @@ exec_terraform() {
     echo "./generate_config.sh"
     echo "     "
     # execute from current folder or -path parameter if exists
+    cd /tf/avm/scripts/bin
     ./generate_config.sh  # Check if the command was successful
     if [ $? -ne 0 ]; then
       echo -e "     "
@@ -148,6 +150,24 @@ exec_terraform() {
       echo -e "     "
       echo -e "\e[32mTerraform $ACTION succeeded!\e[0m"
     fi    
+
+  elif [[ "$ACTION" == *"deploy"* ]]; then
+    echo "     "
+    echo "Running..."
+    echo "./deploy.sh"
+    echo "     "
+    # execute from current folder or -path parameter if exists
+    cd /tf/avm/scripts/bin
+    ./deploy.sh  # Check if the command was successful
+    if [ $? -ne 0 ]; then
+      echo -e "     "
+      echo -e "\e[31mTerraform $ACTION failed. Exiting.\e[0m"
+      exit 1
+    else
+      echo -e "     "
+      echo -e "\e[32mTerraform $ACTION succeeded!\e[0m"
+    fi    
+
   fi  
 
 }
@@ -185,6 +205,7 @@ if [[ $# -lt 1 ]]; then
     echo "tfexe apply run-all -include=/tf/avm/config/path.hcl"
     echo "tfexe import"
     echo "tfexe generate-config"
+    echo "tfexe deploy"
     exit 1
 fi
 
@@ -192,8 +213,8 @@ fi
 ACTION=$1
 shift
 
-if [[ "$ACTION" != "apply" && "$ACTION" != "plan" && "$ACTION" != "init"  && "$ACTION" != "import"  && "$ACTION" != "generate-config" ]]; then
-    echo -e "\e[31mError: First parameter must be 'init' or 'apply' or 'plan' or 'import' or 'generate-config'\e[0m"
+if [[ "$ACTION" != "apply" && "$ACTION" != "plan" && "$ACTION" != "init"  && "$ACTION" != "import"  && "$ACTION" != "generate-config" && "$ACTION" != "deploy" ]]; then
+    echo -e "\e[31mError: First parameter must be 'init' or 'apply' or 'plan' or 'import' or 'generate-config' or 'deploy'\e[0m"
     exit 1
 fi
 
