add deploy-app-lz

diff --git a/scripts/bin/tfexe b/scripts/bin/tfexe
--- a/scripts/bin/tfexe
+++ b/scripts/bin/tfexe
@@ -9,6 +9,7 @@
 # tfexe apply run-all -include=/tf/avm/config/path.hcl"
 # tfexe import # import existing vnet into state file
 # tfexe generate-config # generate config.yaml file based on inputs
+# tfexe deploy-app-lz # execute import, application landing zone and solution accelerators without generate-config file commands
 # tfexe deploy # deploy azure resource based on settings.yaml file and inputs
 # tfexe update-remote-state # refresh config.yaml file to match the current state of the infrastructure
 
@@ -20,10 +21,10 @@ exec_terraform() {
   local TF_VAR_FILE=$3
   local TF_VARS=("${@:4}")
 
-  if [[ "$ACTION" == *"init"* || "$ACTION" == *"plan"* || "$ACTION" == *"apply"* || "$ACTION" == *"import"*  || "$ACTION" == *"generate-config"* || "$ACTION" == *"deploy"* || "$ACTION" == *"update-remote-state"* ]]; then
+  if [[ "$ACTION" == *"init"* || "$ACTION" == *"plan"* || "$ACTION" == *"apply"* || "$ACTION" == *"import"*  || "$ACTION" == *"generate-config"* || "$ACTION" == *"deploy"* || "$ACTION" == *"update-remote-state"* || "$ACTION" == *"deploy-app-lz"* ]]; then
     # alway exec terraform init
 
-    if [[ "$ACTION" != *"import"* && "$ACTION" != *"generate-config"* && "$ACTION" != *"deploy"* && "$ACTION" != *"update-remote-state"* ]]; then
+    if [[ "$ACTION" != *"import"* && "$ACTION" != *"generate-config"* && "$ACTION" != *"deploy"* && "$ACTION" != *"update-remote-state"* && "$ACTION" != *"deploy-app-lz"* ]]; then
 
       echo "Using config file: $TF_CONFIG"
       PREFIX=$(yq  -r '.prefix' $TF_CONFIG)
@@ -185,6 +186,23 @@ exec_terraform() {
       echo -e "\e[32mTerraform $ACTION succeeded!\e[0m"
     fi    
 
+  elif [[ "$ACTION" == *"deploy-app-lz"* ]]; then
+    echo "Go to working directory /tf/avm/scripts/bin"
+    echo "Running..."
+    echo "./deploy_app_lz.sh"
+    echo "     "
+    # execute from current folder or -path parameter if exists
+    cd /tf/avm/scripts/bin
+    ./deploy_app_lz.sh  # Check if the command was successful
+    if [ $? -ne 0 ]; then
+      echo -e "     "
+      echo -e "\e[31mTerraform $ACTION failed. Exiting.\e[0m"
+      exit 1
+    else
+      echo -e "     "
+      echo -e "\e[32mTerraform $ACTION succeeded!\e[0m"
+    fi    
+
   elif [[ "$ACTION" == *"deploy"* ]]; then
     echo "Go to working directory /tf/avm/scripts/bin"
     echo "Running..."
@@ -210,7 +228,7 @@ exec_terraform() {
 
 # Check if at least 2 arguments are provided
 if [[ $# -lt 1 ]]; then
-    echo "Usage: tfexe <init|apply|plan|import|generate-config|deploy|update-remote-state> [-var=key=value | -path=path | -config=configpath]..."
+    echo "Usage: tfexe <init|apply|plan|import|generate-config|deploy|update-remote-state|deploy-app-lz> [-var=key=value | -path=path | -config=configpath]..."
     echo " "
     echo "The available commands for execution are listed below."
     echo "The primary workflow commands are given first, followed by"
@@ -224,6 +242,7 @@ if [[ $# -lt 1 ]]; then
     echo "  generate-config Generate config.yaml file based on inputs"
     echo "  deploy          Deploy azure resource based on settings.yaml file and prompt inputs"
     echo "  update-remote-state  Update remote terraform state with the latest config.yaml file content"
+    echo "  deploy-app-lz   execute 0-launchpad, 1-landingzones and 2-solution_accelerators without generate-config file commands"
 
     echo " "
     echo "All other commands:"
@@ -246,6 +265,7 @@ if [[ $# -lt 1 ]]; then
     echo "tfexe import"
     echo "tfexe generate-config"
     echo "tfexe deploy"
+    echo "tfexe deploy-app-lz"
     echo "tfexe update-remote-state"
     exit 1
 fi
@@ -254,8 +274,8 @@ fi
 ACTION=$1
 shift
 
-if [[ "$ACTION" != "apply" && "$ACTION" != "plan" && "$ACTION" != "init"  && "$ACTION" != "import"  && "$ACTION" != "generate-config" && "$ACTION" != "deploy" && "$ACTION" != "update-remote-state" ]]; then
-    echo -e "\e[31mError: First parameter must be 'init' or 'apply' or 'plan' or 'import' or 'generate-config' or 'deploy' or 'update-remote-state'\e[0m"
+if [[ "$ACTION" != "apply" && "$ACTION" != "plan" && "$ACTION" != "init"  && "$ACTION" != "import"  && "$ACTION" != "generate-config" && "$ACTION" != "deploy" && "$ACTION" != "update-remote-state" && "$ACTION" != "deploy-app-lz" ]]; then
+    echo -e "\e[31mError: First parameter must be 'init' or 'apply' or 'plan' or 'import' or 'generate-config' or 'deploy' or 'update-remote-state or 'deploy-app-lz'\e[0m"
     exit 1
 fi
 
